[project]
name = "curso-backend"
version = "0.1.0"
description = "SeguirÃ© un curso de Youtube de backendd usando FastAPI"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.124.4",
    "pydantic>=2.12.5",
    "uvicorn>=0.38.0",
]
